org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

#aslib gitversion (you can change to "Dev-SNAPSHOT", for last versions)
aslib_version=Release_1.20.1-SNAPSHOT

#mod meta
mod_id=template
mod_version=1.0-SNAPSHOT
mod_name=TEMPLATE
mod_description=
mod_authors=Akaize
mod_license=MIT
mod_homepage=
mod_issues=
mod_icon=assets/template/icon.png

maven_group=v.akfz
archives_base_name=template

#minecraft data
java_version=17
minecraft_version=1.20.1

#mappings
mojang_mappings=1.20.1
parchment_mc_version=1.20.1
parchment_version=2023.09.03

#loaders settings
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=[6.0,6.5)

neoforge_version=20.4.167
neoforge_gradle_version=2.0.173

#mixin
mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT
mixinextras_version=0.4.1